###
//create task in workplace 1
POST http://localhost:8080/1/tasks
Content-Type: application/json

{
  "title": "sampleTask2",
  "description": "desc"
}

###
// get tasks in workplace 1
GET http://localhost:8080/1/tasks
###
// delete task in workplace 1 with task id 3
DELETE http://localhost:8080/1/tasks/2
###
// get task with id 2 from workplace 1
GET http://localhost:8080/1/tasks/2
###
// get recurrence of task 1 in workplace 1
GET http://localhost:8080/1/tasks/2/recurrence
###
// add recurrence to task 1 in workplace 1
POST http://localhost:8080/1/tasks/2/recurrence
Content-Type: application/json

{
  "days": ["THURSDAY"],
  "time" : "15:32"
}
###
PUT http://localhost:8080/1/tasks/2/toggle-active
###
PUT http://localhost:8080/1/tasks/2/set_category/2
###
// add group to task
PUT http://localhost:8080/1/tasks/2/add_group/4