###
//create task in workplace 1
POST http://localhost:8080/1/tasks
Content-Type: application/json

{
  "title": "sampleTask1",
  "description": "desc"
}

###
// get your tasks in workplace 1
GET http://localhost:8080/1/tasks
###
// delete task in workplace with task id
DELETE http://localhost:8080/1/tasks/1
###
// get all tasks
GET http://localhost:8080/1/tasks/all
###
// get recurrence of task 1 in workplace 1
GET http://localhost:8080/1/tasks/1/recurrence
###
// add recurrence to task 1 in workplace 1
POST http://localhost:8080/1/tasks/2/recurrence
Content-Type: application/json

{
  "days": ["MONDAY"],
  "time" : "17:02"
}
###
PUT http://localhost:8080/1/tasks/2/toggle-active
###
PUT http://localhost:8080/1/tasks/2/set_category/1
###
// add group to task
PUT http://localhost:8080/1/tasks/2/add_group/3