###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "sampleOwner",
  "password": "coderslab"
}
###
//login owner
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=sampleOwner&password=coderslab

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "sampleUser",
  "password": "coderslab"
}
###
//login user
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=sampleUser&password=coderslab
###
DELETE http://localhost:8080/remove-account


###
GET http://localhost:8080/workplaces/1/profiles

###
PUT http://localhost:8080/workplaces/1/profiles/2/set-group/3