###
//create workplace
POST http://localhost:8080/workplaces
Content-Type: application/json

{
  "name": "sampleWorkplace"
}

###
//get workplaces
GET http://localhost:8080/workplaces

###
//get workplace by id
GET http://localhost:8080/workplaces/1

###
//join workplace
PUT http://localhost:8080/workplaces/join/1
###
//edit workplace
PUT http://localhost:8080/workplaces
Content-Type: application/json

{
  "id" : 1,
  "name" : "workplaceWithEditedName"
}
###
//delete workplace
DELETE http://localhost:8080/workplaces/1

###
//quit workplace
PUT http://localhost:8080/workplaces/leave/1