###

GET http://localhost:8080/1/groups

###
POST http://localhost:8080/1/groups
Content-Type: application/json

{
  "name" : "waiter"
}

###

PUT http://localhost:8080/1/groups
Content-Type: application/json

{
  "id" : 2,
  "name" : "cook"
}

###

DELETE http://localhost:8080/1/groups/3